<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getMessagesFrom($date, $user)
    {
        $query = $this->createQueryBuilder('m')
            ->select('m, s, r')
            ->join('m.sender', 's')
            ->leftJoin('m.receiver', 'r')
            ->where('m.created >= :date')
            ->andWhere('m.sender = :user OR m.receiver = :user OR m.receiver IS NULL')
            ->setParameter('date', $date)
            ->setParameter('user', $user)
            ->orderBy('m.created', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
